In [1]:
import pandas as pd
df = pd.read_csv('../data/raw/Dataset.csv')
df.info()        # info() shows columns, non null count and dtypes

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [2]:
df.head(10)     # Shows initial 10 rows of the dataset

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
5,s9,TV Show,The Great British Baking Show,Andy Devonshire,United Kingdom,9/24/2021,2021,TV-14,9 Seasons,"British TV Shows, Reality TV"
6,s10,Movie,The Starling,Theodore Melfi,United States,9/24/2021,2021,PG-13,104 min,"Comedies, Dramas"
7,s939,Movie,Motu Patlu in the Game of Zones,Suhas Kadav,India,5/1/2021,2019,TV-Y7,87 min,"Children & Family Movies, Comedies, Music & Mu..."
8,s13,Movie,Je Suis Karl,Christian Schwochow,Germany,9/23/2021,2021,TV-MA,127 min,"Dramas, International Movies"
9,s940,Movie,Motu Patlu in Wonderland,Suhas Kadav,India,5/1/2021,2013,TV-Y7,76 min,"Children & Family Movies, Music & Musicals"

SEARCHING FOR DISGUISED/HIDDEN MISSING VALUES: info() shows no nulls, missing values might be disguised.
Checks in order: empty strings → whitespace-only cells → text placeholders

In [3]:
(df == '').sum()   # Checks each cells of each column where a value though empty, was recorded

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [4]:
for col in ['director','country','date_added']:
    whitespace_count = df[col].str.strip().eq('').sum()
    print(f"{col}: {whitespace_count} whitespace-only entries")     # Strip spaces, then test for emptiness: catches cells that contain only spaces

director: 0 whitespace-only entries
country: 0 whitespace-only entries
date_added: 0 whitespace-only entries

In [5]:
df['director'].unique()[:30]  # First 30 distinct values

<StringArray>
[                                       'Kirsten Johnson',
                                        'Julien Leclercq',
                                          'Mike Flanagan',
                                          'Bruno Garotti',
                                           'Haile Gerima',
                                        'Andy Devonshire',
                                         'Theodore Melfi',
                                            'Suhas Kadav',
                                    'Christian Schwochow',
                                              'Not Given',
                        'Krysia Plonka, Kristian Mercado',
                           'Mark Thornton, Todd Kauffman',
                          'Robert Cullen, José Luis Ucha',
                                      'Kongkiat Komesiri',
          'Pedro de Echave García, Pablo Azorín Williams',
                                       'Anirban Majumder',
                                        'Olivier Megaton',
                                'Alex Woo, Stanley Moore',
                                             'S. Shankar',
                                           'Dennis Dugan',
                                          'Scott Stewart',
                                         'Robert Luketic',
                                            'Rajiv Menon',
                                             'Adam Salky',
                                         'K.S. Ravikumar',
 'Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket Chaudhary',
                                           'Daniel Sandu',
                                         'Cédric Jimenez',
                                           'George Nolfi',
                                         'Bunmi Ajakaiye']
Length: 30, dtype: str

From the first 30 distinct directors, the text 'Not Given' appears. This means some titles have no director recorded.

In [6]:
df['director'].value_counts().get('Not Given',0)     # Counts how many cells have 'Not Given' as their value in the director column

np.int64(2588)

There are 2588 titles with missing directors(disguised as 'Not Given').

In [7]:
df['country'].unique()[:30]    # First 30 distinct values.

<StringArray>
[ 'United States',         'France',         'Brazil', 'United Kingdom',
          'India',        'Germany',       'Pakistan',      'Not Given',
          'China',   'South Africa',          'Japan',        'Nigeria',
          'Spain',    'Philippines',      'Australia',      'Argentina',
         'Canada',      'Hong Kong',          'Italy',    'New Zealand',
          'Egypt',       'Colombia',         'Mexico',        'Belgium',
    'Switzerland',         'Taiwan',       'Bulgaria',         'Poland',
    'South Korea',   'Saudi Arabia']
Length: 30, dtype: str

From a sample of first 30 distinct values, 'Not Given' text was found.

In [8]:
df['country'].value_counts().get('Not Given',0)     # Counts how many cells have 'Not Given' as their value in the country column

np.int64(287)

There are 287 titles with missing country (disguised as 'Not Given').

In [9]:
df['date_added'].unique()[:30]    # First 30 distinct values

<StringArray>
[ '9/25/2021',  '9/24/2021',  '9/22/2021',   '5/1/2021',  '9/23/2021',
  '5/21/2021',  '7/13/2021',  '6/12/2021',   '5/7/2021', '11/26/2019',
  '6/15/2018',  '5/18/2018',  '6/18/2019',  '9/21/2021',  '9/20/2021',
  '9/19/2021',  '9/17/2021',  '9/14/2021',  '9/10/2021',   '9/9/2021',
   '9/7/2021',   '9/2/2021',   '9/1/2021',  '8/28/2021',  '8/29/2021',
  '9/16/2021',   '4/7/2021',  '8/27/2021',  '9/15/2021',   '7/7/2021']
Length: 30, dtype: str

Date_added column is of string datatype.

In [10]:
pd.to_datetime(df['date_added'], errors= 'coerce').isna().sum()  # TEST ONLY: checks how many dates would fail to convert from str to date— does not change df yet

np.int64(0)

0 failure = date_added is safe to convert.

INSPECTING DIRECTOR & COUNTRY FOR THE NUMBER OF DISTINCT VALUES

In [11]:
print(df['director'].nunique())   # counts distinct director values — includes 'Not Given' as one category at this stage
print(df['country'].nunique())    # counts distinct country values — includes 'Not Given' as one category at this stage

4528
86

In [12]:
df['rating'].unique()      # Finds unique values from the column

<StringArray>
[   'PG-13',    'TV-MA',    'TV-PG',    'TV-14',    'TV-Y7',     'TV-Y',
       'PG',     'TV-G',        'R',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

14 unique values including both 'NR' (not rated) and 'UR' (unrated).

INSPECTING THE REMAINING COLUMNS:

In [13]:
for col in ['duration','listed_in','type','title','show_id']:
    print(col, ':', df[col].unique()[:10] if df[col].nunique()<20 else f"{df[col].nunique()} unique values")
    # for each column: show all unique values if fewer than 20 exist, otherwise just show the total count

duration : 220 unique values
listed_in : 513 unique values
type : <StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str
title : 8787 unique values
show_id : 8790 unique values

Title has 8787 distinct values but there are 8790 rows.

INSPECTING DUPLICATE TITLES IF ANY EXIST:

In [14]:
df[df.duplicated('title', keep=False)].sort_values('title') # (keep=False)- marks every occurence of a repeated title (not just the later ones).

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

3 pairs of duplicate titles were found.

RELOADING THE DATASET

The raw CSV was re-downloaded to rule out accidental edits on my side. The same three date-formatted titles ('15-Aug', '22-Jul', '9-Feb') were present, so they exist in the source data. A title can legitimately be a date, so titles were left unchanged.

In [15]:
import os
print(os.path.getmtime('../data/raw/Dataset.csv')) # last-modified timestamp of the raw file, in raw Unix seconds
print(os.path.getsize('../data/raw/Dataset.csv')) # file size in bytes — used to confirm which file version is loaded

1790435737.5016594
1071619

In [16]:
import datetime
print(datetime.datetime.fromtimestamp(os.path.getmtime('../data/raw/Dataset.csv'))) 
# converts the raw Unix timestamp above into a human-readable date and time,
# to confirm the raw CSV was actually updated when I redownloaded it

2026-09-26 20:45:37.501659

In [17]:
df.duplicated().sum()  # checks for fully identical rows across ALL columns, not just title

np.int64(0)

Unique show_id differs in every row, so it can hide true duplicates.

DUPLICATE CHECK THAT IGNORES show_id : TO FIND THE REAL DUPLICATE RECORD IF EXIST

In [18]:
cols_without_id = df.columns.drop('show_id').tolist()  # every column except show_id
print(df.duplicated(subset=cols_without_id).sum())

3

STANDARDIZATION CHECKS :

In [19]:
# type column
df['type'].value_counts()  # column check for inconsistent labels and its value count

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [20]:
# country column
df['country'].str.contains(',', na=False).sum() # Does any country cell hold more than one country (comma-separated)?

np.int64(0)

In [21]:
# do any text columns have leading/trailing spaces hiding in real values?
for col in ['type', 'title', 'director', 'country', 'rating','duration', 'listed_in']:
    print(col, ":", (df[col].dropna() != df[col].dropna().str.strip()).sum())

type : 0
title : 1
director : 0
country : 0
rating : 0
duration : 0
listed_in : 0

Title column has one value/cell having leading/trailing spaces.

In [22]:
# shows the rows whoses titles have extra leading/ trailing spaces
df[df['title'] != df['title'].str.strip()]

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
4718,s6530,Movie,Consequences,Ozan Açıktan,Turkey,10/25/2019,2014,TV-MA,106 min,"Dramas, International Movies, Thrillers"

RECHECKING DUPLICATE TITLES AFTER REMOVING SPACES:

In [23]:
stripped_titles = df['title'].str.strip()
df[stripped_titles.duplicated(keep=False)].sort_values('title')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
2590,s3372,Movie,Consequences,Ozan Açıktan,Turkey,10/25/2019,2014,TV-MA,106 min,"Dramas, International Movies, Thrillers"
4718,s6530,Movie,Consequences,Ozan Açıktan,Turkey,10/25/2019,2014,TV-MA,106 min,"Dramas, International Movies, Thrillers"

Four pairs of duplicates are found in the dataset.

INSPECTING COUNTRY FOR SPELLING VARIANT :

In [24]:
# prints every distinct country name, sorted, to scan for spelling variants
for c in sorted(df['country'].dropna().unique()):
    print(c)

Argentina
Australia
Austria
Bangladesh
Belarus
Belgium
Brazil
Bulgaria
Cambodia
Cameroon
Canada
Chile
China
Colombia
Croatia
Cyprus
Czech Republic
Denmark
Egypt
Finland
France
Georgia
Germany
Ghana
Greece
Guatemala
Hong Kong
Hungary
Iceland
India
Indonesia
Iran
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kenya
Kuwait
Lebanon
Luxembourg
Malaysia
Mauritius
Mexico
Mozambique
Namibia
Netherlands
New Zealand
Nigeria
Norway
Not Given
Pakistan
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Romania
Russia
Saudi Arabia
Senegal
Serbia
Singapore
Slovenia
Somalia
South Africa
South Korea
Soviet Union
Spain
Sweden
Switzerland
Syria
Taiwan
Thailand
Turkey
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Venezuela
Vietnam
West Germany
Zimbabwe

Titles labelled with countries ('Soviet Union', 'West Germany') that no longer exist

In [25]:
# counts titles labelled with countries that no longer exist
df['country'].isin(['Soviet Union', 'West Germany']).sum()

np.int64(2)

'Soviet Union' and 'West Germany' kept as-it-is: only 2 rows affected, and remapping to modern country names (e.g. Russia, Germany) would misrepresent historical fact

In [26]:
# counts titles per rating label
df['rating'].value_counts()

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

Rating NR has 79 and UR has 3 value count.

In [27]:
# Task 1: Netflix Data Cleaning & Preparation
# Consolidated cleaning steps based on inspection findings above :

# 1. Replace 'Not Given' placeholder text with real NaN in director and country columns.
#    Turns 'Not Given' text into a true blank, so summaries and counts automatically
#    skip these rows instead of accidentally counting 'Not Given' as if it were a real answer.
df['director'] = df['director'].replace('Not Given', pd.NA)
df['country'] = df['country'].replace('Not Given', pd.NA)

# 2. Convert date_added from text to an actual datetime type.
#    Enables chronological sorting, filtering, and year/month extraction later.
df['date_added'] = pd.to_datetime(df['date_added'], format='%m/%d/%Y')

# 3. Remove leading/trailing spaces from titles.
df['title'] = df['title'].str.strip()

# 4. Standardize rating labels: UR (Unrated) and NR (Not Rated) mean the same thing.
#    Folding into NR since it has far more rows (79 vs 3).
df['rating'] = df['rating'].replace('UR', 'NR')

# 5. 'Soviet Union' and 'West Germany' kept as-it-is: only 2 rows affected, and remapping to
#    modern country names (e.g. Russia, Germany) would misrepresent historical fact. No code needed.

# 6. Remove duplicate records.
#    "A duplicate = identical in every column EXCEPT show_id.This covers the 3 date-formatted like title pairs AND the 'Consequences' pair".
cols_without_id = df.columns.drop('show_id').tolist()

#  Audit trail: view exactly which rows are about to be removed
removed_rows = df[df.duplicated(subset=cols_without_id, keep='first')]
print(f"Rows to be removed: {len(removed_rows)}") # expect 4
print(removed_rows[['show_id', 'title', 'type']])

df= df.drop_duplicates(subset=cols_without_id, keep='first')

# 7. Reset the index after dropping rows, so the DataFrame has clean, sequential row numbers.
df = df.reset_index(drop=True)  # (drop=True)- discards the old index

# Sanity check: confirm final row count and remaining data-quality counts.
print(f"Final row count: {len(df)}")            # expect 8790 - 4 = 8786
print(df['director'].isna().sum(), "rows with missing director (now proper NaN)")   # expect 2587 and not 2588(as one duplicate pair had no directors)
print(df['country'].isna().sum(), "rows with missing country (now proper NaN)")     # expect 287
print(df['rating'].value_counts().get('UR', 0), "rows still labelled UR")           # expect 0
print(df[df['title'] != df['title'].str.strip()].shape[0], "titles with stray spaces")  # expect 0

Rows to be removed: 4
     show_id         title     type
537    s5965         9-Feb  TV Show
4260   s5966        22-Jul    Movie
4261   s5967        15-Aug    Movie
4718   s6530  Consequences    Movie
Final row count: 8786
2587 rows with missing director (now proper NaN)
287 rows with missing country (now proper NaN)
0 rows still labelled UR
0 titles with stray spaces

In [28]:
# Post-cleaning verification 
# assert <condition>, "message": silent if True; stops the notebook if False
df.info()   # confirm column dtypes after cleaning

# show_id must still be unique
assert df['show_id'].is_unique, "Duplicate show_id values found"

# No duplicate records, ignoring show_id
assert df.duplicated(subset=cols_without_id).sum() == 0, "Duplicate records remain (ignoring show_id)"

# date_added is a real datetime column with no missing values
#    (is_datetime64_any_dtype is used because the exact dtype varies by pandas version)
assert pd.api.types.is_datetime64_any_dtype(df['date_added']), "date_added is not a datetime column"
assert df['date_added'].notna().all(), "date_added contains missing values"

# release_year in a plausible range
assert df['release_year'].between(1900, 2021).all(), "release_year outside 1900-2021"

print("ALL CHECKS PASSED")

<class 'pandas.DataFrame'>
RangeIndex: 8786 entries, 0 to 8785
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8786 non-null   str
 1   type          8786 non-null   str
 2   title         8786 non-null   str
 3   director      6199 non-null   str
 4   country       8499 non-null   str
 5   date_added    8786 non-null   datetime64[us]
 6   release_year  8786 non-null   int64
 7   rating        8786 non-null   str
 8   duration      8786 non-null   str
 9   listed_in     8786 non-null   str
dtypes: datetime64[us](1), int64(1), str(8)
memory usage: 686.5 KB
ALL CHECKS PASSED

EXPORTING THE CLEANED DATA FOR ANALYSIS:

In [29]:
df.to_csv('../data/cleaned/netflix_cleaned.csv', index=False)